### ISSUE TITLE
openSnackbar doesn't work

### ISSUE THREAD

**Issue by beppek** [reftoken/blockscope-ui#25]
The openSnackbar function doesn't work when imported (for example in reftoken-frontend) which causes the entire application to crash. Since the function is called on every error in reftoken-frontend this is a very high priority bug which needs to be fixed as soon as possible.

**Comment by fmenkes** [comment]
First thing in the morning!

**Comment by fmenkes** [comment]
https://github.com/reftoken/reftoken-frontend/issues/91#issuecomment-467013194

**Comment by beppek** [comment]
closing this, see [this comment](https://github.com/reftoken/reftoken-frontend/issues/91#issuecomment-467183373)
